[package]
name = "chamber-ui"
version = "0.1.0"
edition = "2024"
description = "TUI interface for Chamber secrets manager"

[dependencies]
chamber-vault = {workspace = true}
chamber-password-gen = {workspace = true}
chamber-import-export = {workspace = true}
anyhow = { workspace = true }
crossterm = { workspace = true }
dirs = { workspace = true }
ratatui = { workspace = true }
arboard = { workspace = true }
time = {workspace = true}