[package]
name = "chamber-cli"
version = "0.1.0"
edition = "2024"
description = "CLI interface for Chamber secrets manager"

[dependencies]
anyhow = { workspace = true }
chamber-vault = { workspace = true }
chamber-import-export = { workspace = true  }
chamber-password-gen = { workspace = true  }
clap = { workspace = true }
rpassword = { workspace = true }

[dev-dependencies]
time = "0.3.41"