name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: chamber
            asset_name: chamber-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: chamber.exe
            asset_name: chamber-windows-amd64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: chamber
            asset_name: chamber-macos-amd64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: chamber
            asset_name: chamber-linux-amd64-static
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: chamber
            asset_name: chamber-linux-arm64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            artifact_name: chamber
            asset_name: chamber-linux-arm64-static

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y lld clang

      - name: Install MUSL targets
        if: matrix.os == 'ubuntu-latest' && contains(matrix.target, 'musl')
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Install cross-compilation tools
        if: matrix.os == 'ubuntu-latest' && contains(matrix.target, 'aarch64')
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build
        run: cargo build --target ${{ matrix.target }} --release
      
      # Rename the binary to match the asset name to avoid conflicts
      - name: Rename binary
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            # Windows binary already has .exe extension
            cp ./target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ./${{ matrix.asset_name }}
          else
            # Linux and macOS binaries
            cp ./target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ./${{ matrix.asset_name }}
          fi
        shell: bash
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ./${{ matrix.asset_name }}

  create-release:
    name: Create Release
    needs: build-and-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      
      # Debug: List what was downloaded
      - name: List artifacts
        run: |
          echo "Contents of ./artifacts:"
          find ./artifacts -type f -ls
      
      # Move files to have unique names in the root artifacts directory
      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          
          # Move each file from its subdirectory to the release-assets directory
          # The subdirectories are named after the artifact names
          if [ -f "./artifacts/chamber-linux-amd64/chamber-linux-amd64" ]; then
            cp "./artifacts/chamber-linux-amd64/chamber-linux-amd64" ./release-assets/
          fi
          
          if [ -f "./artifacts/chamber-windows-amd64.exe/chamber-windows-amd64.exe" ]; then
            cp "./artifacts/chamber-windows-amd64.exe/chamber-windows-amd64.exe" ./release-assets/
          fi
          
          if [ -f "./artifacts/chamber-macos-amd64/chamber-macos-amd64" ]; then
            cp "./artifacts/chamber-macos-amd64/chamber-macos-amd64" ./release-assets/
          fi
          
          echo "Contents of ./release-assets:"
          ls -la ./release-assets/
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ./release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}